name: GitHub Actions
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v2
          - name: Retrieve information from package.json
            uses: myrotvorets/info-from-package-json-action@1.0.0
            id: ver
          - name: Unit testing
            uses: actions/setup-node@v2
            with:
              node-version: '14'
          - run: npm install
          - run: npm test
          - name: Create Release
            id: create_release
            uses: actions/create-release@v1
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            with:
              tag_name: ${{ steps.ver.outputs.packageVersion }}
              release_name: Release ${{ steps.ver.outputs.packageVersion }}
              body: |
                Seule compte la résistance silencieuse d’un petit nombre, dont la présence impassible de “convives de pierre” sert à créer de nouveaux rapports, de nouvelles distances, de nouvelles valeurs, et permet de constituer un pôle qui, s’il n’empêche certes pas ce monde d’égarés d’être ce qu’il est, transmettra pourtant à quelques-uns la sensation de la vérité, sensation qui sera peut-être aussi le début de quelque crise libératrice.
                - Julius Evola - Révolte contre le monde moderne
              draft: false
              prerelease: false
