name: GitHub Actions
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v2
          - run: git config --global user.name 'Enzo Do rosario'
          - run: git config --global user.email 'dorosario.enzo@gmail.com'
          - run: npm version patch -m "[RELEASE] %s"
          - run: git push
          - name: Retrieve information from package.json
            uses: myrotvorets/info-from-package-json-action@1.0.0
            id: ver
          - name: Unit testing
            uses: actions/setup-node@v2
            with:
              node-version: '14'
          - run: npm install
          - run: npm test
          - name: Release
            uses: softprops/action-gh-release@v1
            with:
              body: |
                À mes yeux, le nationalisme n'a jamais eu qu'un sens : vivre et agir avec assez d'intensité pour susciter dans les regards d'autrui le respect et l'esprit d'émulation.
                - Hjalmar Schacht - Mémoire d'un magicien
              files: main.js
              tag_name: ${{ steps.ver.outputs.packageVersion }}
              name: Release ${{ steps.ver.outputs.packageVersion }}
